kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
      volumes:
        - /tmp/cache:/cache
  
  
  - name: install
    image: node
    commands:
      - npm install


  - name: test
    image: node
    commands:
      - npm test


  - name: build
    image: node
    commands:
      - npm run build


  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: 207.246.92.195
      username: drone
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      target: /home/drone/deployment
      source:
        - dist/*


  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
      volumes:
        - /tmp/cache:/cache
    when:
      branch: master


