name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.18.2'
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: Rsync Deployments Action
      uses: Burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ./dist
        remote_path: /home/drone/deployment
        remote_host: 207.246.92.195
        remote_user: drone
        remote_key: ${{ secrets.DEPLOY_KEY }}
