name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.18.2'
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: deploy
      uses: noobly314/deploy-with-scp@v1
      with:
        server-ip: 207.246.92.195
        username: drone
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        proxy-server-ip: 104.156.249.245
        proxy-username: bastion
        proxy-ssh-key: ${{ secrets.PROXY_KEY }}
        src: ./dist
        dest: ./deployment

