name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.18.2'
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: deploy
      uses: appleboy/scp-action@master
      with:
        host: 207.246.92.195
        username: drone
        key: ${{ secrets.DEPLOY_KEY }}
        proxy_host: 104.156.249.245
        proxy_username: bastion
        proxy_key: ${{ secrets.PROXY_KEY }}
        source: ./dist
        target: ./deployment
